In [2]:
#numpy is fixed type and is much faster than lists since numpy uses less memory

In [4]:
#numpy utilizes contiguous memory, list doesnt

In [5]:
import numpy as np

In [6]:
a=np.array([1,3,5])
b=np.array([1,2,3])

In [7]:
a*b

array([ 1,  6, 15])

In [8]:
a = np.array([1,2,3], dtype='int32')
print(a)


[1 2 3]


In [9]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)


[[9. 8. 7.]
 [6. 5. 4.]]


In [10]:
# Get Dimension
a.ndim


1

In [11]:
# Get Size
a.itemsize

4

In [12]:
# Get total size
a.nbytes

12

In [13]:
# Get number of elements
a.size

3

In [14]:
#accessing specific element

a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [15]:
# Get a specific element [r, c]
a[1, 5]

13

In [16]:
# Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [17]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [19]:
#[startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [20]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [21]:
#3D example

In [22]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
# Get specific element (work outside in)
b[0,1,1]

4

In [25]:
# replace 
b[:,1,:] = [[9,9],[8,8]]
#must replace to same dimension or else error

In [26]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [28]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [29]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [30]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.42446539, 0.23927715],
       [0.42896073, 0.2556097 ],
       [0.22999608, 0.4499859 ],
       [0.87558327, 0.07424892]])

In [31]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[ 2,  7,  0],
       [-4, -3,  0],
       [-1,  7,  5]])

In [32]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [34]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [36]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [37]:
a + 2


array([3, 4, 5, 6])

In [38]:
a-2

array([-1,  0,  1,  2])

In [39]:
a*2

array([2, 4, 6, 8])

In [40]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [44]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [45]:
a ** 2

array([ 1,  4,  9, 16])

In [46]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [47]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [48]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [50]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html


In [51]:
stats = np.array([[1,2,3],[4,5,6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
np.min(stats)

1

In [53]:
np.max(stats, axis=1)

array([3, 6])

In [54]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [55]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [56]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [62]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1   2   3  45   5   6   9   5  43  43]
 [ 53   4   5  43 645  46  65  87   5  36]
 [  5  36   7  46  72 236  63  63   6  46]
 [ 53  52   6  46  46   7  89  68  54   3]]


In [63]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True, False, False,  True,
         True],
       [ True,  True,  True,  True, False,  True, False, False,  True,
         True],
       [False, False,  True,  True,  True,  True, False, False, False,
         True]])